version: "3"

services:

  ckan-dev:
    container_name: ckan-dev
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
    networks:
      - auroral_network



    

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"
    networks:
      - auroral_network
    

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auroral_network
    

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    networks:
      - auroral_network
    

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - auroral_network
   

  # monitor:
  #   build: 
  #     context: ./service_monitor
  #   image: monitor_container
  #   container_name: monitor
  #   volumes:
  #     - ./src:/app/src
  #     # - /CKAN_Junio2023/src/ckanext-testapi/ckanext/testapi:/app/testapi
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - ckan-dev
  #   networks:
  #     - auroral_network
    
networks:
  auroral_network:
    external: true
 

volumes:
  ckan_storage:
  pg_data:
  solr_data:
